---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::html_document2: default
  bookdown::word_document2: default
  bookdown::pdf_document2:
    template: templates/brief_template.tex
documentclass: book
#bibliography: references.bib
---

# Introduction {-}


```{r, include=knitr::is_latex_output(), echo = FALSE}
# Add marker on the header of the page only in LaTeX environment.
# Without this piece of code, LaTeX would print in the header
# the name of the previous chapter, that is List of Tables
knitr::asis_output('\\markboth{\\MakeUppercase{Introduction}}{\\MakeUppercase{Introduction}}')
```


<!-- # Introduction -->

<!-- \adjustmtc  -->
<!-- For PDF output, we must include this LaTeX command after unnumbered headings, otherwise the numbers in the mini table of contents will be incorrect -->

This thesis has been conceived from my two-years experience in the pricing department of a non-life insurance company. During this period I had the opportunity to deeply understand how a pricing team works and which are the needs of the insurance business. With this work we are trying to merge the theoretical expertise from the academic world with the practical experience from the business world, aiming to produce valuable results that will have a meaningful impact on the actuarial practice.

Within this thesis we will describe some of the advancements of the statistical techniques commonly adopted in non-life insurance pricing and we will discuss how they can satisfy the pricing specific needs.

To do so, we firstly have to describe the non-life insurance pricing framework from the definition of the fundamental concepts <!--, such as how insurance contracts work and what risk modeling means, --> to the illustration of the dynamics distinctive of this business.

Due to the intrinsic characteristics of the topic, in this thesis we will keep a multidisciplinary approach. We won't just compare the models from a statistical point of view, but we will also take important actuarial considerations, touching aspects from various subjects, such as law, economics, finance, risk management and marketing.
In our dissertation, we will also make a specific focus on data science, as in the last years the technological development and the growing availability of data made advanced analytics integral parts of the actuarial science. 
By discussing the solutions proposed we will also comment some implementation issues from a computer science perspective.

All these aspects underline that the actuary, to carry out his profession, needs a wide range of skills that goes from the most technical one, such as understanding the statistical models or being able to conduct risk management evaluations, to the more business oriented ones, such as understanding the market characteristics and the customers behavior.

This thesis is organized into 3 parts:

\begin{itemize}[itemsep=2pt]
\item In chapter \ref{chap:nlip} we will describe in general how non-life insurance pricing works starting from the definition of insurance contract, developing the discussion around technical pricing and making some considerations on price optimization;
\item In chapter \ref{chap:models} we will illustrate some statistical techniques suitable for price modeling and we will comment how they fit the pricing needs; we will start from the Generalized Linear Model (GLM), that is the most employed model in technical pricing today, to then present some of its advancements;
\item In chapter \ref{chap:practical-app} we will present a practical application on a real-world actuarial dataset of the models described in section \ref{chap:models} and we will compare their performances.
\end{itemize}

At the end of chapter \@ref(chap:nlip) we will make a digression on the actuary role in the pricing framework and at the end of chapter \@ref(chap:models) we will comment the importance of his supervision in the modeling process.







